type Provider = "gemini" | "openai";

export type TextGenerationResult = {
  text: string;
  provider: Provider;
  finishReason: string | null;
};

class AiProviderError extends Error {
  provider: Provider;
  status: number;
  raw: string;

  constructor(provider: Provider, message: string, status = 500, raw = "") {
    super(message);
    this.name = "AiProviderError";
    this.provider = provider;
    this.status = status;
    this.raw = raw;
  }
}

function buildGeminiBody(prompt: string, maxOutputTokens: number) {
  return {
    contents: [
      {
        parts: [
          {
            text: prompt,
          },
        ],
      },
    ],
    generationConfig: {
      temperature: 0.7,
      topK: 40,
      topP: 0.95,
      maxOutputTokens,
    },
  };
}

async function resolveGeminiModel(apiKey: string): Promise<string> {
  let modelName = "gemini-1.5-flash";

  try {
    const modelsUrl = `https://generativelanguage.googleapis.com/v1/models?key=${apiKey}`;
    const modelsResponse = await fetch(modelsUrl);

    if (!modelsResponse.ok) {
      const errorText = await modelsResponse.text();
      console.error("Failed to list Gemini models:", errorText);
      return modelName;
    }

    const modelsData = await modelsResponse.json();
    const availableModel = modelsData.models?.find(
      (model: { name?: string; supportedGenerationMethods?: string[] }) =>
        model.supportedGenerationMethods?.includes("generateContent"),
    );

    if (availableModel?.name) {
      return availableModel.name.replace(/^models\//, "");
    }

    if (modelsData.models?.length > 0 && modelsData.models[0]?.name) {
      return modelsData.models[0].name.replace(/^models\//, "");
    }
  } catch (error) {
    console.error("Error listing Gemini models:", error);
  }

  return modelName;
}

function extractGeminiText(data: any): TextGenerationResult {
  if (data?.error) {
    throw new AiProviderError(
      "gemini",
      data.error.message || "Failed to generate Gemini response",
      500,
      JSON.stringify(data),
    );
  }

  const candidate = data?.candidates?.[0];
  const text =
    candidate?.content?.parts
      ?.map((part: { text?: string }) => part?.text ?? "")
      .join("")
      .trim() ?? "";

  if (!text) {
    throw new AiProviderError(
      "gemini",
      "No text was generated by Gemini.",
      500,
      JSON.stringify(data),
    );
  }

  return {
    text,
    provider: "gemini",
    finishReason: candidate?.finishReason ?? null,
  };
}

async function callGemini(
  apiKey: string,
  prompt: string,
  maxOutputTokens: number,
): Promise<TextGenerationResult> {
  const modelName = await resolveGeminiModel(apiKey);
  const body = JSON.stringify(buildGeminiBody(prompt, maxOutputTokens));
  const urls = [
    `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`,
    `https://generativelanguage.googleapis.com/v1/models/${modelName}:generateContent?key=${apiKey}`,
  ];

  let lastError: AiProviderError | null = null;

  for (const url of urls) {
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body,
    });

    if (!response.ok) {
      const errorText = await response.text();
      lastError = new AiProviderError(
        "gemini",
        parseProviderErrorMessage(
          errorText,
          "Failed to generate Gemini response",
        ),
        response.status,
        errorText,
      );
      console.error(`Gemini API error for ${url}:`, errorText);
      continue;
    }

    return extractGeminiText(await response.json());
  }

  throw (
    lastError ??
    new AiProviderError("gemini", "Failed to generate Gemini response")
  );
}

function extractOpenAiText(data: any): TextGenerationResult {
  const text = data?.choices?.[0]?.message?.content?.trim?.() ?? "";

  if (!text) {
    throw new AiProviderError(
      "openai",
      "No text was generated by OpenAI.",
      500,
      JSON.stringify(data),
    );
  }

  return {
    text,
    provider: "openai",
    finishReason: data?.choices?.[0]?.finish_reason ?? null,
  };
}

async function callOpenAi(
  apiKey: string,
  prompt: string,
  maxOutputTokens: number,
): Promise<TextGenerationResult> {
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4o-mini",
      temperature: 0.7,
      max_tokens: maxOutputTokens,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error("OpenAI API error:", errorText);
    throw new AiProviderError(
      "openai",
      parseProviderErrorMessage(
        errorText,
        "Failed to generate OpenAI response",
      ),
      response.status,
      errorText,
    );
  }

  return extractOpenAiText(await response.json());
}

export function parseProviderErrorMessage(
  raw: string,
  fallback: string,
): string {
  try {
    const errorData = JSON.parse(raw);
    if (errorData.error?.message) {
      return errorData.error.message;
    }
  } catch {
    if (raw && raw.length < 300) {
      return raw;
    }
  }

  return fallback;
}

function isGeminiQuotaError(error: unknown): boolean {
  if (!(error instanceof AiProviderError) || error.provider !== "gemini") {
    return false;
  }

  if (error.status === 429) {
    return true;
  }

  return /(quota|resource_exhausted|rate limit|too many requests|exceeded)/i.test(
    `${error.message}\n${error.raw}`,
  );
}

export async function generateSkinDiseaseText(
  prompt: string,
  maxOutputTokens: number,
): Promise<TextGenerationResult> {
  const geminiApiKey = process.env.GEMINI_API_KEY?.trim();
  const openAiApiKey = process.env.OPENAI_API_KEY?.trim();

  if (!geminiApiKey && !openAiApiKey) {
    throw new Error("Neither Gemini nor OpenAI API key is configured");
  }

  if (geminiApiKey) {
    try {
      return await callGemini(geminiApiKey, prompt, maxOutputTokens);
    } catch (error) {
      if (openAiApiKey && isGeminiQuotaError(error)) {
        console.warn(
          "Gemini quota exceeded for skin disease AI route. Falling back to OpenAI.",
        );
        return callOpenAi(openAiApiKey, prompt, maxOutputTokens);
      }

      throw error;
    }
  }

  return callOpenAi(openAiApiKey!, prompt, maxOutputTokens);
}

export function formatSkinDiseaseAiError(
  error: unknown,
  fallback: string,
): { message: string; status: number } {
  if (error instanceof AiProviderError) {
    return {
      message: error.message || fallback,
      status: error.status || 500,
    };
  }

  if (error instanceof Error) {
    return {
      message: error.message || fallback,
      status: 500,
    };
  }

  return {
    message: fallback,
    status: 500,
  };
}
